---
minimum_pre_commit_version: 3.0.0
repos:
  - repo: local
    hooks:
      - id: export-hooks
        name: Export .pre-commit-hooks.yaml
        language: system
        entry: python -m ahooks.export
        args: [-h]
        pass_filenames: false
        files: ^hooks/.*\.py$
        stages: [pre-commit, pre-push]
      - id: emit-requirements
        name: Emit requirements.txt from pyproject.toml using `uv`
        language: system
        entry: python -m ahooks.emit_requirements
        pass_filenames: false
        files: ^(pyproject\.toml|requirements\.txt)$
        stages: [pre-commit, pre-push]
...
