repos: 
    - repo: local 
    hooks: 
        - id: emit-requirements
          name: Emit requirements.txt from pyproject.toml using `uv`
          entry: python scripts/emit_requirements.py
          language: system
          pass_filenames: False
          files: ^(pyproject\.toml|requirements\.txt)$
          stages: [pre-commit, pre-push]
        - id: block-manual-req-edits
          name: Block manual requirements.txt edits 
          entry: |
            bash -c 
            if git diff --cached --name-only | grep -q "^requirements\.txt$" &&
                ! git diff --cached --name-only | grep -q "^pyproject\.toml$"; then
                echo "Edit pyproject.toml and run the emitter; don't hand-edit requirements.txt."
                exit 1
            fi
          language: system
          pass_filenames: false 
          files: ^requirements\.txt$
          stages: [pre-commit, pre-push]
