[project]
name = "ahooks"
version = "0.1.0"
description = "Single python package for all the pre-commit hooks I use."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "click>=8.1.8",
    "tomli>=2.2.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
